name: 26ef2b
version: 1.21.0
appVersion: 6.9.0
description: DataDog Agent
keywords:
- monitoring
- alerting
- metric
home: https://www.datadoghq.com
icon: http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
maintainers:
- name: hkaj
  email: haissam@datadoghq.com
- name: irabinovitch
  email: ilan@datadoghq.com
- name: xvello
  email: xavier.vello@datadoghq.com
- name: charlyf
  email: charly@datadoghq.com
